

const actionTypes = {
    // Actions related to Messages/Emails
    REFRESH_MESSAGES: 'REFRESH_MESSAGES', 
    GET_MESSAGES_BEGIN : 'GET_MESSAGES_BEGIN',
    GET_MESSAGES_SUCCESS : 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE : 'GET_MESSAGES_FAILURE', 

    GET_MESSAGES_COUNT_SUCCESS : 'GET_MESSAGES_COUNT_SUCCESS',
    GET_MESSAGES_COUNT_FAILURE : 'GET_MESSAGES_COUNT_FAILURE',
    MARK_MESSAGES_COUNT_SUCCESS : 'MARK_MESSAGES_COUNT_SUCCESS',

    ADD_MESSAGE_BEGIN : 'ADD_MESSAGE_BEGIN',
    ADD_MESSAGE_SUCCESS : 'ADD_MESSAGE_SUCCESS',
    ADD_MESSAGE_FAILURE : 'ADD_MESSAGE_FAILURE',

    DELETE_MESSAGE_BEGIN: 'DELETE_MESSAGE_BEGIN',
    DELETE_MESSAGE_SUCCESS : 'DELETE_MESSAGE_SUCCESS',
    DELETE_MESSAGE_FAILURE : 'DELETE_MESSAGE_FAILURE',

    GET_MESSAGE_BEGIN : 'GET_MESSAGE_BEGIN',
    GET_MESSAGE_SUCCESS : 'GET_MESSAGE_SUCCESS',
    GET_MESSAGE_FAILURE : 'GET_MESSAGE_FAILURE',
    MARK_MESSAGE_AS_VIEWED : 'MARK_MESSAGE_AS_VIEWED',

    TOGGLE_STAR : 'TOGGLE_STAR',
    TOGGLE_STAR_SUCCESS : 'TOGGLE_STAR_SUCCESS',
    TOGGLE_STAR_FAILURE : 'TOGGLE_STAR_FAILURE',


    FILL_MY_INBOX_SUCCESS : 'FILL_MY_INBOX_SUCCESS',


    // Actions related to Todos
    ADD_TODO_SUCCESS : 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE : 'ADD_TODO_FAILURE',
    
    GET_TODOS_BEGIN : 'GET_TODOS_BEGIN',
    GET_TODOS_SUCCESS : 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE : 'GET_TODOS_FAILURE',

    DELETE_TODO : 'DELETE_TODO',
    DELETE_TODO_SUCCESS : 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAILURE : 'DELETE_TODO_FAILURE',

    TOGGLE_TODO_STATUS : 'TOGGLE_TODO_STATUS',
    TOGGLE_TODO_STATUS_SUCCESS : 'TOGGLE_TODO_STATUS_SUCCESS',
    TOGGLE_TODO_STATUS_FAILURE : 'TOGGLE_TODO_STATUS_FAILURE',

    UPDATE_TODO : 'UPDATE_TODO',
    UPDATE_TODO_SUCCESS : 'UPDATE_TODO_SUCCESS',
    UPDATE_TODO_FAILURE : 'UPDATE_TODO_FAILURE',


    // Other actions
    TOGGLE_SIDE_DRAWER : 'TOGGLE_SIDE_DRAWER',
    AUTH_BEGIN : 'AUTH_BEGIN',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_FAILURE : 'AUTH_FAILURE',
    AUTH_SIGNOUT : 'AUTH_SIGNOUT'
}

export default actionTypes;